SELECT 'TRUE' as IS_SUB,KIND,COUNT(*) as AMOUNT FROM VISITOR JOIN TICKET ON VISITOR.ID = VISITOR_ID
WHERE IS_SUBSCRIPTION = 'TRUE'
GROUP BY KIND
UNION
SELECT 'FALSE' as IS_SUB,KIND,COUNT(*) as AMOUNT FROM VISITOR JOIN TICKET ON VISITOR.ID =VISITOR_ID
WHERE IS_SUBSCRIPTION = 'FALSE'
GROUP BY KIND
